spring:
  datasource:
    url: jdbc:mysql://rm-wz9857sgx78431278o.mysql.rds.aliyuncs.com/traning
    driver-class-name: com.mysql.jdbc.Driver
    username: training
    password: Gdkyit2017#
server:
  port: 9090
